version: '3'
services:
  mongo:
    container_name: facilita
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: facilita
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: